version: '3.3'

services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - '54320:5432'
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
